app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

api_fight_show:
    path:     /api/walki/{id}
    controller: AppBundle\Controller\Api\FightController::showAction
    condition: 'request.isXmlHttpRequest()'
    requirements:
            id: '\d+'

api_fight_list:
    path:     /api/turnieje/walki
    controller: AppBundle\Controller\Api\FightController::listAction
    condition: 'request.isXmlHttpRequest()'
    requirements:
        id: '\d+'

api_signup_show:
    path:     /api/zapisy/{id}
    controller: AppBundle\Controller\Api\SignUpController::showAction
    condition: 'request.isXmlHttpRequest()'
    requirements:
            id: '\d+'

api_signup_list:
    path:     /api/tournaments/{id}/signups
    controller: AppBundle\Controller\Api\SignUpController::list
    methods: GET
    condition: 'request.isXmlHttpRequest()'
    requirements:
        id: '\d+'

api_signup_new:
    path:     /api/zapisy/
    controller: AppBundle\Controller\Api\SignUpController::newAction
    condition: 'request.isXmlHttpRequest()'

api_club_list:
    path:     /api/kluby
    condition: 'request.isXmlHttpRequest()'
    controller: AppBundle\Controller\Api\ClubController::listAction

api_tournament_show:
    path:     /api/turnieje/{id}
    condition: 'request.isXmlHttpRequest()'
    controller: AppBundle\Controller\Api\TournamentController::showAction

api_tournament_fight_list:
    path:     /api/turnieje/{id}/walki
    controller: AppBundle\Controller\Api\TournamentController::showFights
    condition: 'request.isXmlHttpRequest()'
    requirements:
        id: '\d+'

admin_api_user_list:
    path:     /admin/api/users
    condition: 'request.isXmlHttpRequest()'
    controller: AppBundle\Controller\Admin\Api\UserController::indexAction

admin_api_tournament_list:
    path:     /admin/api/tournaments
    condition: 'request.isXmlHttpRequest()'
    controller: AppBundle\Controller\Admin\Api\TournamentController::list

api_image_upload:
    path:     /api/images
    controller: AppBundle\Controller\Api\ImageController::upload